@startuml
class User{
    id: varchar(36) (uuid4), primarykey
    name: varchar(255), notnull
    role_id: varchar(36), notnull
    email: varchar(255), unique
}

User::country_id --> Country::id
User::role_id --> Role::id

class CustomerData {
    id: varchar(36), primarykey
    user_id: varchar(36), unique, notnull
    customer_number, varchar(255), notnull
    country_id: varchar(36), notnull
}

CustomerData::user_id --> User::id

class UserDeviceGroupRelation {
    id: varchar(36), primarykey
    user_id: varchar(36), notnull
    device_group_id: varchar(36), notnull
}

UserDeviceGroupRelation::user_id -> User::id
UserDeviceGroupRelation::device_group_id -> DeviceGroup::id

class Country{
    id: varchar(36), primarykey
    name: varchar(255), notnull
    code_2: varchar(2), notnull
    code_3: varchar(3), notnull
}

class Role {
    id: varchar(36), primarykey
    name: varchar(255), notnull
}

class Log {
    id: varchar(36), primarykey
    user_id: varchar(36), notnull
    data: text, notnull
    timestamp: datetime, notnull
}

Log::user_id --> User::id

class DeviceType {
    id: varchar(36), primarykey
    name: varchar(255), notnull, unique
}

class DeviceModel {
    id: varchar(36), primarykey
    device_type_id: varchar(36), notnull
    name: varchar(255) notnull
}

DeviceModel::device_type_id --> DeviceType::id

class Device {
    id: varchar(36), primarykey
    device_model_id: varchar(36), notnull
    serial_number: varchar(50), notnull, unique
    equimpent_number: varchar(50), notnull
    suffix: varchar(50), notnull
    customer_id: varchar(36), notnull
    enabled: bool, notnull
}

Device::device_model_id --> DeviceModel::id

class DeviceDeviceGroupRelation {
    id: varchar(36), primarykey
    device_id: varchar(36), notnull
    device_group_id: varchar(36), notnull
}

DeviceDeviceGroupRelation::device_id -> Device::id
DeviceDeviceGroupRelation::device_group_id -> DeviceGroup::id

class DeviceGroup {
    id: varchar(36), primarykey
    name: varchar(255), notnull
}

class Document{
    id: varchar(36), primarykey
    device_id: varchar(36), notnull
    upload_date: datetime, notnull
    file_name: varchar(255), notnull
    file_content: longblob, notnull
    file_size: int, notnull
    event_code: varchar(16)
    event_message: varchar(255)
}
Document::device_id --> Device::id

class Notification {
    id: varchar(36), primarykey
    user_id: varchar(36)
    device_id: varchar(36)
    timestamp: datetime, notnull
    is_sent: bool, notnull
    content: text, notnull
}

Notification::user_id --> User::id
Notification::device_id --> Device::id

class DeviceStat {
    id: varchar(36), primarykey
    device_id: varchar(36), notnull, unique
    active_since: timestamp
    last_upload_timestamp: timestamp
    total_file_count: int
    total_sent_bytes: bigint
    max_file_size: int
    firmware_version: varchar(32)
    windows_version: varchar(64)
    app_version: varchar(32)
}

DeviceStat::device_id --> Device::id

@enduml
