@startuml

entity "User" as User {
    *id : varchar(36) (uuid4)
    --
    name : varchar(255)
    role_id : varchar(36)
    email : varchar(255)
}

entity "Country" as Country {
    *id : varchar(36)
    --
    name : varchar(255)
    code_2 : varchar(2)
    code_3 : varchar(3)
}

entity "Role" as Role {
    *id : varchar(36)
    --
    name : varchar(255)
}

entity "CustomerData" as CustomerData {
    *id : varchar(36)
    --
    user_id : varchar(36)
    customer_number : varchar(255)
    country_id : varchar(36)
}

entity "UserDeviceGroupRelation" as UserDeviceGroupRelation {
    *id : varchar(36)
    --
    user_id : varchar(36)
    device_group_id : varchar(36)
}

entity "DeviceGroup" as DeviceGroup {
    *id : varchar(36)
    --
    name : varchar(255)
}

entity "Log" as Log {
    *id : varchar(36)
    --
    customer_id : varchar(36)
    data : text
    timestamp : datetime
}

entity "DeviceType" as DeviceType {
    *id : varchar(36)
    --
    name : varchar(255)
}

entity "DeviceModel" as DeviceModel {
    *id : varchar(36)
    --
    device_type_id : varchar(36)
    name : varchar(255)
}

entity "Device" as Device {
    *id : varchar(36)
    --
    device_model_id : varchar(36)
    serial_number : varchar(50)
    equimpent_number : varchar(50)
    suffix : varchar(50)
    customer_id : varchar(36)
    enabled : bool
}

entity "DeviceDeviceGroupRelation" as DeviceDeviceGroupRelation {
    *id : varchar(36)
    --
    device_id : varchar(36)
    device_group_id : varchar(36)
}

entity "Document" as Document {
    *id : varchar(36)
    --
    device_id : varchar(36)
    upload_date : datetime
    file_name : varchar(255)
    file_content : longblob
    file_size : int
    event_code : varchar(16)
    event_message : varchar(255)
}

entity "Notification" as Notification {
    *id : varchar(36)
    --
    user_id : varchar(36)
    device_id : varchar(36)
    timestamp : datetime
    is_sent : bool
    content : text
}

entity "DeviceStat" as DeviceStat {
    *id : varchar(36)
    --
    device_id : varchar(36)
    active_since : timestamp
    last_upload_timestamp : timestamp
    total_file_count : int
    total_sent_bytes : bigint
    max_file_size : int
    firmware_version : varchar(32)
    windows_version : varchar(64)
    app_version : varchar(32)
}

User }o--|| Role : role_id
CustomerData ||--|| User : user_id
CustomerData }o--|| Country : country_id
UserDeviceGroupRelation }o--|| User : user_id
UserDeviceGroupRelation }o--|| DeviceGroup : device_group_id
Log }o--|| CustomerData : customer_id
DeviceModel }o--|| DeviceType : device_type_id
Device }o--|| DeviceModel : device_model_id
Device }o--|| CustomerData : customer_id
DeviceDeviceGroupRelation }o--|| Device : device_id
DeviceDeviceGroupRelation }o--|| DeviceGroup : device_group_id
Document }o--|| Device : device_id
Notification }o--o| User : user_id
Notification }o--o| Device : device_id
DeviceStat ||--|| Device : device_id

@enduml
