CREATE USER dev_user IDENTIFIED BY "password123";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO dev_user;

CREATE USER prod_user IDENTIFIED BY "password123";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO prod_user;
